// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFhnIk_12dQjodf7HEmycpC30NsJkAzgY',
    appId: '1:729771004180:web:681a721270d472dfbc7201',
    messagingSenderId: '729771004180',
    projectId: 'fireexpapp',
    authDomain: 'fireexpapp.firebaseapp.com',
    storageBucket: 'fireexpapp.firebasestorage.app',
    measurementId: 'G-98W99VWBCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2OwzCCBFbO9RWF2aUgCN2cP6wVGde5YA',
    appId: '1:729771004180:android:a28a028da93712a2bc7201',
    messagingSenderId: '729771004180',
    projectId: 'fireexpapp',
    storageBucket: 'fireexpapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtKQiIMugz9EqKvKsDd85snuOpELlmaiU',
    appId: '1:729771004180:ios:6f668e9a395ea45bbc7201',
    messagingSenderId: '729771004180',
    projectId: 'fireexpapp',
    storageBucket: 'fireexpapp.firebasestorage.app',
    iosBundleId: 'com.example.fireExpApp',
  );

}